export interface ImageData {
  cache_ref: string;
  thumb_base64: string;
  width: number;
  height: number;
  mode: string;
}

export type BaseDataTypes = number | string | ImageData;

export interface StructDescr {
  structureType: "list" | "dict";
  itemsType: string | UnionDescr;
}

export interface UnionDescr {
  anyOf: string[];
}

export interface FieldDataWrapper {
  type: string | StructDescr | UnionDescr;
  value: BaseDataTypes | null;
}

// This is a frontend-only type that extends FieldDataWrapper with UI state
export interface FrontendFieldDataWrapper extends FieldDataWrapper {
  _selectedType?: string;
  _showPreview?: boolean;
  _structuredInputType?: "list" | "dict";
  _inputMode?: number;
}

export interface FunctionSchema {
  name: string;
  callableId: string;
  category: string[];
  filePath: string;
  doc?: string | null;
  arguments: Record<string, FrontendFieldDataWrapper>;
  dynamicInputType?: StructDescr | null;
  outputStyle?: "single" | "multiple";
  outputs: Record<string, FrontendFieldDataWrapper>;
  autoGenerated?: boolean;
  [key: string]: unknown;
}
