export type BaseDataTypes = number | string;

export interface StructuredDataDescription {
  structureType: "list" | "dict";
  items: string;
}

export interface FieldDataWrapper {
  type: string | StructuredDataDescription;
  value: BaseDataTypes | null;
}

export interface FunctionSchema {
  name: string;
  callableId: string;
  category: string[];
  filePath: string;
  doc: string | null;
  arguments: Record<string, FieldDataWrapper>;
  dynamicInputType: StructuredDataDescription | null;
  outputStyle: "single" | "multiple";
  outputs: Record<string, FieldDataWrapper>;
  autoGenerated: boolean;
}
