import { createWithEqualityFn } from "zustand/traditional";
import { persist, type PersistOptions } from "zustand/middleware";
import { shallow } from "zustand/shallow";
import type { StateCreator } from "zustand";

export interface NodeFunctionData {
  name: string;
  group: string;
  category: string[];
  arguments: Record<
    string,
    {
      type: string;
      default_value?: any;
    }
  >;
  dynamicInputType?: {
    structureType: string;
    items: string;
  };
  return: {
    type: string;
  };
  autoGenerated: boolean;
}

export interface NodesResponse {
  [functionName: string]: NodeFunctionData;
}

type SchemasStoreState = {
  nodeSchemas: NodesResponse;
};

type SchemasStoreActions = {
  setNodeSchemas: (nodeSchemas: NodesResponse) => void;
  fetchNodeSchemas: () => Promise<void>;
};

export type SchemasState = SchemasStoreState & SchemasStoreActions;

type SchemasPersist = (
  config: StateCreator<SchemasState>,
  options: PersistOptions<SchemasState>,
) => StateCreator<SchemasState>;

const useSchemasStore = createWithEqualityFn<SchemasState>(
  (persist as SchemasPersist)(
    (set) => ({
      nodeSchemas: {},

      setNodeSchemas: (nodeSchemas) => set({ nodeSchemas }),

      fetchNodeSchemas: async () => {
        try {
          const response = await fetch("http://localhost:8000/nodes");
          const data = await response.json();
          console.log("node schemas:", data);
          set({ nodeSchemas: data });
        } catch (error) {
          console.error("Failed to fetch node schemas:", error);
        }
      },
    }),
    {
      name: "schemas-storage",
    },
  ),
  shallow,
);

export default useSchemasStore;
