import { createWithEqualityFn } from "zustand/traditional";
import { shallow } from "zustand/vanilla/shallow";

export interface NodeFunctionData {
  name: string;
  group: string;
  category: string[];
  arguments: Record<
    string,
    {
      type: string;
      default_value?: any;
    }
  >;
  dynamicInputType?: {
    structureType: string;
    items: string;
  };
  return: {
    type: string;
  };
  autoGenerated: boolean;
}

export interface NodesResponse {
  [functionName: string]: NodeFunctionData;
}

type SchemasStoreState = {
  nodeSchemas: NodesResponse;
};

type SchemasStoreActions = {
  setNodeSchemas: (nodeSchemas: NodesResponse) => void;
  fetchNodeSchemas: () => Promise<void>;
};

export type SchemasState = SchemasStoreState & SchemasStoreActions;

const useSchemasStore = createWithEqualityFn<SchemasState>(
  (set) => ({
    nodeSchemas: {},

    setNodeSchemas: (nodeSchemas) => set({ nodeSchemas }),

    fetchNodeSchemas: async () => {
      try {
        const response = await fetch("http://localhost:8000/nodes");
        const data = await response.json();
        console.log("node schemas:", data);
        set({ nodeSchemas: data });
      } catch (error) {
        console.error("Failed to fetch node schemas:", error);
      }
    },
  }),
  shallow,
);

export default useSchemasStore;
